spring:
  application:
    name: rml-bff-BFF_PROJECT

server:
  port: ${SERVER_PORT:8081}
  parallelism: ${SERVER_PARALLELISM:200}

# URLs dos SRV services — via K8s ClusterIP (service name do K8s)
clients:
  srv-product:
    url: ${SRV_PRODUCT_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c

springdoc:
  swagger-ui:
    path: /swagger-ui.html
